/**
 * formatter.js – Build the GitHub PR comment markdown from merged agent results.
 */

import { decisionBadge } from "../utils/riskEngine.js";

export function formatSummaryComment(review, repo) {
  const { decision, agent_summaries } = review;
  const lines = [];
  const dedupedIssues = dedupeIssues(review.issues || []);
  const fileImpact = buildFileImpactRows(dedupedIssues);
  const keyFindings = dedupedIssues.slice(0, 5);

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# 🤖 AI Code Review — Summary");
  lines.push("");
  lines.push(
    "> 3 specialized AI agents: Security · Performance · Code Quality"
  );
  lines.push("");

  // ── Assessment ─────────────────────────────────────────────────────────
  lines.push("## ✅ Assessment");
  lines.push("");
  lines.push(`- **Decision (Approve / Needs Changes / Reject):** ${decisionBadge(decision)}`);
  lines.push(`- **Summary:** ${review.overall_assessment}`);
  lines.push(`- **Total Findings:** ${dedupedIssues.length}`);
  lines.push("");

  // ── Agent Summaries ─────────────────────────────────────────────────────
  lines.push("## 🧠 Agent Highlights");
  lines.push("");
  lines.push(`- **🔒 Security:** ${agent_summaries.security || "No security issues found."}`);
  lines.push(`- **⚡ Performance:** ${agent_summaries.performance || "No performance issues found."}`);
  lines.push(`- **🧹 Code Quality:** ${agent_summaries.code_quality || "No code quality issues found."}`);
  lines.push("");

  // ── Changed File Impact ────────────────────────────────────────────────
  if (fileImpact.length > 0) {
    lines.push("## 📁 Changed File Impact");
    lines.push("");
    lines.push("| File | Findings | Highest Severity | Effect |");
    lines.push("|------|----------|------------------|--------|");
    for (const row of fileImpact) {
      lines.push(`| \`${row.file}\` | ${row.count} | ${severityBadge(row.highestSeverity)} | ${row.effect} |`);
    }
    lines.push("");
  }

  // ── Key Findings ───────────────────────────────────────────────────────
  if (keyFindings.length > 0) {
    lines.push(`## 🚨 Key Findings (${keyFindings.length})`);
    lines.push("");
    lines.push("| Severity | Location | Issue | Suggested Fix |");
    lines.push("|----------|----------|-------|---------------|");
    for (const finding of keyFindings) {
      const location = finding.line ? `\`${finding.file}\`:${finding.line}` : `\`${finding.file}\``;
      lines.push(
        `| ${severityBadge(finding.severity)} | ${location} | ${escapePipes(finding.issue)} | ${escapePipes(finding.suggestion || "Apply validation/config-based fix") } |`
      );
    }
    lines.push("");

    const suggestions = keyFindings.filter((f) => f.suggested_code);
    if (suggestions.length > 0) {
      lines.push("## 💡 Suggested Code");
      lines.push("");
      for (let i = 0; i < suggestions.length; i++) {
        const s = suggestions[i];
        const location = s.line ? `\`${s.file}\`:${s.line}` : `\`${s.file}\``;
        lines.push(`### ${i + 1}. ${location}`);
        lines.push("```suggestion");
        lines.push(s.suggested_code);
        lines.push("```");
        lines.push("");
      }
    }
  }

  // ── Regressions ─────────────────────────────────────────────────────────
  if (review.bad_regressions?.length) {
    lines.push("## ❌ Regressions");
    lines.push("");
    for (const b of review.bad_regressions.slice(0, 5)) lines.push(`- ${b}`);
    lines.push("");
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push(
    `*Generated by **AI Multi-Agent PR Review Bot** for \`${repo}\` PR #${review.pr_number}*`
  );

  return lines.join("\n");
}

function dedupeIssues(issues) {
  const severityOrder = { High: 0, Medium: 1, Low: 2 };
  const map = new Map();

  for (const issue of issues) {
    const file = issue.file || "unknown";
    const line = issue.line || "";
    const key = `${file}|${line}|${(issue.issue || "").toLowerCase().trim()}`;

    if (!map.has(key)) {
      map.set(key, {
        ...issue,
        file,
        agents: [issue.agent].filter(Boolean),
      });
      continue;
    }

    const existing = map.get(key);
    const existingRank = severityOrder[existing.severity] ?? 3;
    const incomingRank = severityOrder[issue.severity] ?? 3;

    if (incomingRank < existingRank) {
      existing.severity = issue.severity;
    }
    if (!existing.suggestion && issue.suggestion) {
      existing.suggestion = issue.suggestion;
    }
    if (!existing.suggested_code && issue.suggested_code) {
      existing.suggested_code = issue.suggested_code;
    }
    if (issue.agent && !existing.agents.includes(issue.agent)) {
      existing.agents.push(issue.agent);
    }
  }

  return [...map.values()].sort((a, b) => {
    const rankA = severityOrder[a.severity] ?? 3;
    const rankB = severityOrder[b.severity] ?? 3;
    if (rankA !== rankB) return rankA - rankB;
    return (a.file || "").localeCompare(b.file || "");
  });
}

function buildFileImpactRows(issues) {
  const severityOrder = { High: 0, Medium: 1, Low: 2 };
  const fileMap = new Map();

  for (const issue of issues) {
    const file = issue.file || "unknown";
    if (!fileMap.has(file)) {
      fileMap.set(file, { file, count: 0, highestSeverity: "Low" });
    }

    const row = fileMap.get(file);
    row.count += 1;

    const currentRank = severityOrder[row.highestSeverity] ?? 3;
    const incomingRank = severityOrder[issue.severity] ?? 3;
    if (incomingRank < currentRank) {
      row.highestSeverity = issue.severity;
    }
  }

  return [...fileMap.values()]
    .map((row) => ({
      ...row,
      effect: summarizeEffect(row.highestSeverity, row.count),
    }))
    .sort((a, b) => {
      const rankA = severityOrder[a.highestSeverity] ?? 3;
      const rankB = severityOrder[b.highestSeverity] ?? 3;
      if (rankA !== rankB) return rankA - rankB;
      return b.count - a.count;
    });
}

function summarizeEffect(severity, count) {
  if (severity === "High") return count > 1 ? "High impact on correctness" : "Potential correctness break";
  if (severity === "Medium") return count > 1 ? "Moderate behavior risk" : "Minor behavior risk";
  return count > 1 ? "Low impact cleanup needed" : "Low impact";
}

function severityBadge(severity) {
  const map = {
    High: "🔴 High",
    Medium: "🟡 Medium",
    Low: "🟢 Low",
  };
  return map[severity] || "⚪ Unknown";
}

function escapePipes(text = "") {
  return String(text).replace(/\|/g, "\\|");
}
