/**
 * formatter.js – Build the GitHub PR comment markdown from merged agent results.
 */

import { riskEmoji, decisionBadge } from "../utils/riskEngine.js";

export function formatSummaryComment(review, repo) {
  const { risk_score, risk_level, decision, agent_scores, agent_summaries } = review;
  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# 🤖 PR Review Autopilot — Multi-Agent Analysis");
  lines.push("");
  lines.push(
    "> Powered by **3 specialized AI agents** running in parallel: Security · Performance · Code Quality"
  );
  lines.push("");

  // ── Risk Dashboard ───────────────────────────────────────────────────────
  lines.push("## 🎯 Risk Dashboard");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(
    `| **Overall Risk Score** | ${riskEmoji(risk_level)} **${risk_score} / 100** *(higher = riskier)* |`
  );
  lines.push(`| **Risk Level** | ${riskEmoji(risk_level)} **${risk_level}** |`);
  lines.push(`| **Decision** | ${decisionBadge(decision)} |`);
  lines.push(`| **Assessment** | ${review.overall_assessment} |`);
  lines.push("");

  // ── Agent Scores ─────────────────────────────────────────────────────────
  lines.push("## 🧠 Agent Scores *(0 = safe, 100 = critical risk)*");
  lines.push("");
  lines.push("| Agent | Score | Level |");
  lines.push("|-------|-------|-------|");

  const agentLevels = {
    security: scoreToLevel(agent_scores.security),
    performance: scoreToLevel(agent_scores.performance),
    code_quality: scoreToLevel(agent_scores.code_quality),
  };

  lines.push(
    `| 🔒 Security Agent | **${agent_scores.security}** | ${riskEmoji(agentLevels.security)} ${agentLevels.security} |`
  );
  lines.push(
    `| ⚡ Performance Agent | **${agent_scores.performance}** | ${riskEmoji(agentLevels.performance)} ${agentLevels.performance} |`
  );
  lines.push(
    `| 🧹 Code Quality Agent | **${agent_scores.code_quality}** | ${riskEmoji(agentLevels.code_quality)} ${agentLevels.code_quality} |`
  );
  lines.push("");

  // ── Agent Summaries ───────────────────────────────────────────────────────
  lines.push("## 📋 Agent Summaries");
  lines.push("");
  lines.push(`**🔒 Security:** ${agent_summaries.security || "No security issues found."}`);
  lines.push("");
  lines.push(
    `**⚡ Performance:** ${agent_summaries.performance || "No performance issues found."}`
  );
  lines.push("");
  lines.push(
    `**🧹 Code Quality:** ${agent_summaries.code_quality || "No code quality issues found."}`
  );
  lines.push("");

  // ── Issues ─────────────────────────────────────────────────────────────
  const issues = review.issues || [];
  if (issues.length > 0) {
    lines.push(`## 🚨 Issues Found (${issues.length} total)`);
    lines.push("");

    // Sort by severity: High → Medium → Low
    const order = { High: 0, Medium: 1, Low: 2 };
    const sorted = [...issues].sort(
      (a, b) => (order[a.severity] ?? 3) - (order[b.severity] ?? 3)
    );

    for (let i = 0; i < sorted.length; i++) {
      const iss = sorted[i];
      const sevEmoji = { High: "🔴", Medium: "🟡", Low: "🟢" }[iss.severity] ?? "⚪";
      lines.push(
        `### ${i + 1}. ${sevEmoji} [${iss.severity}] \`${iss.file || "unknown"}\` — *${iss.agent} Agent*`
      );
      if (iss.line) lines.push(`> Line ${iss.line}`);
      lines.push("");
      lines.push(`**Issue:** ${iss.issue}`);
      lines.push(`**Risk:** ${iss.risk}`);
      lines.push(`**Fix:** ${iss.suggestion}`);
      if (iss.suggested_code) {
        lines.push("```suggestion");
        lines.push(iss.suggested_code);
        lines.push("```");
      }
      lines.push("");
    }
  }

  // ── Good Improvements ────────────────────────────────────────────────────
  if (review.good_improvements?.length) {
    lines.push("## ✅ Good Improvements");
    lines.push("");
    for (const g of review.good_improvements) lines.push(`- ${g}`);
    lines.push("");
  }

  // ── Bad Regressions ──────────────────────────────────────────────────────
  if (review.bad_regressions?.length) {
    lines.push("## ❌ Bad Regressions");
    lines.push("");
    for (const b of review.bad_regressions) lines.push(`- ${b}`);
    lines.push("");
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push(
    `*Generated by **AI Multi-Agent PR Review Bot** for \`${repo}\` PR #${review.pr_number}*`
  );

  return lines.join("\n");
}

function scoreToLevel(score) {
  if (score <= 20) return "Low";
  if (score <= 50) return "Medium";
  if (score <= 75) return "High";
  return "Critical";
}
